# On you termonal please run command:
# docker compose up -d

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=census_app
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
